### ISSUE TITLE
Demo username / password

### ISSUE THREAD

**Issue by harikt** [bseries/demo#1]
Hi there, 

I discovered something today :) . Tried admin@example.com / secret . 

May be you can provide a username / password on the demo page ?

Thank you.

**Comment by mariuswilms** [comment]
Hi Hari,

thanks for the interest. Unfortunately the demo site is only semi public and we can't provide an official login. Doing so would require us to tightly sandbox the web application, which is possible but we don't have the resources for. Fortunately I can offer you a personal login, just email me at b@atelierdisko.de. Thanks!
